namespace TiendaLinea.Models
{
    /// <summary>
    /// Values of <see cref="Usuario.UserType"/>. NOT generated by scaffolding — the database only
    /// stores this column as a plain string (it was written by the discriminator of the original
    /// code-first Table-per-Hierarchy mapping, back when Cliente/Empleado/Administrador were
    /// separate C# classes with real inheritance). Database-first scaffolding cannot recover that
    /// inheritance hierarchy from a single table plus a string column, so it produces one flat
    /// <see cref="Usuario"/> class instead; the application layer (see UI/AppState.cs) is what
    /// now tells the three "kinds" of user apart, using these same string values so existing rows
    /// keep meaning what they meant before.
    /// </summary>
    public static class UserTypes
    {
        public const string Cliente        = "Cliente";
        public const string Empleado       = "Empleado";
        public const string Administrador  = "Administrador";
    }
}
